import type { DemoState } from './domain'

function daysAgo(days: number, hour = 9): string {
  const date = new Date()
  date.setDate(date.getDate() - days)
  date.setHours(hour, 15, 0, 0)
  return date.toISOString()
}

export function createDemoState(): DemoState {
  return {
    version: 1,
    term: {
      id: 'term-2569-1',
      label: 'ภาคเรียนที่ 1/2569',
      isActive: true,
      startsOn: '2026-05-18',
      endsOn: '2026-10-09',
    },
    accounts: [
      {
        id: 'acc-student-01',
        username: '69001',
        password: 'demo1234',
        displayName: 'นักเรียนตัวอย่าง 01',
        role: 'student',
        studentId: 'student-01',
      },
      {
        id: 'acc-teacher-01',
        username: 'teacher.demo',
        password: 'demo1234',
        displayName: 'ครูตัวอย่าง',
        role: 'teacher',
        teacherId: 'teacher-01',
      },
      {
        id: 'acc-admin-01',
        username: 'admin.demo',
        password: 'demo1234',
        displayName: 'ผู้ดูแลระบบตัวอย่าง',
        role: 'admin',
      },
    ],
    students: [
      {
        id: 'student-01',
        studentCode: '69001',
        name: 'นักเรียนตัวอย่าง 01',
        classroomId: 'class-m2-1',
        classroomName: 'ม.2/1',
        score: 92,
        status: 'active',
      },
      {
        id: 'student-02',
        studentCode: '69002',
        name: 'นักเรียนตัวอย่าง 02',
        classroomId: 'class-m2-1',
        classroomName: 'ม.2/1',
        score: 100,
        status: 'active',
      },
      {
        id: 'student-03',
        studentCode: '69003',
        name: 'นักเรียนตัวอย่าง 03',
        classroomId: 'class-m2-1',
        classroomName: 'ม.2/1',
        score: 87,
        status: 'active',
      },
      {
        id: 'student-04',
        studentCode: '69004',
        name: 'นักเรียนต่างห้องตัวอย่าง',
        classroomId: 'class-m3-1',
        classroomName: 'ม.3/1',
        score: 96,
        status: 'active',
      },
    ],
    teachers: [
      {
        id: 'teacher-01',
        name: 'ครูตัวอย่าง',
        classroomIds: ['class-m2-1'],
      },
    ],
    rules: [
      {
        id: 'rule-late',
        category: 'การมาเรียน',
        title: 'มาโรงเรียนสาย',
        points: 2,
        severity: 'low',
        guardianContactRequired: false,
        active: true,
      },
      {
        id: 'rule-hair',
        category: 'ทรงผม',
        title: 'ทรงผมไม่เป็นไปตามระเบียบ',
        points: 3,
        severity: 'medium',
        guardianContactRequired: false,
        active: true,
      },
      {
        id: 'rule-uniform',
        category: 'การแต่งกาย',
        title: 'แต่งกายไม่เรียบร้อย',
        points: 5,
        severity: 'medium',
        guardianContactRequired: false,
        active: true,
      },
      {
        id: 'rule-bullying',
        category: 'ความปลอดภัย',
        title: 'กลั่นแกล้งผู้อื่น',
        points: 15,
        severity: 'serious',
        guardianContactRequired: true,
        active: true,
      },
      {
        id: 'rule-fight',
        category: 'ความปลอดภัย',
        title: 'ทะเลาะวิวาท',
        points: 20,
        severity: 'critical',
        guardianContactRequired: true,
        active: true,
      },
    ],
    transactions: [
      {
        id: 'tx-student-01-a',
        studentId: 'student-01',
        termId: 'term-2569-1',
        kind: 'deduction',
        requestedDelta: -5,
        appliedDelta: -5,
        scoreBefore: 97,
        scoreAfter: 92,
        ruleId: 'rule-uniform',
        reason: 'แต่งกายไม่เรียบร้อยตามระเบียบที่กำหนด',
        occurredAt: daysAgo(1, 10),
        actorId: 'acc-teacher-01',
      },
      {
        id: 'tx-student-01-b',
        studentId: 'student-01',
        termId: 'term-2569-1',
        kind: 'deduction',
        requestedDelta: -3,
        appliedDelta: -3,
        scoreBefore: 100,
        scoreAfter: 97,
        ruleId: 'rule-hair',
        reason: 'ทรงผมไม่เป็นไปตามระเบียบ',
        occurredAt: daysAgo(3, 8),
        actorId: 'acc-teacher-01',
      },
      {
        id: 'tx-student-03-b',
        studentId: 'student-03',
        termId: 'term-2569-1',
        kind: 'addition',
        requestedDelta: 2,
        appliedDelta: 2,
        scoreBefore: 85,
        scoreAfter: 87,
        reason: 'ทำกิจกรรมปรับพฤติกรรมครบถ้วน',
        occurredAt: daysAgo(2, 14),
        actorId: 'acc-admin-01',
      },
      {
        id: 'tx-student-03-a',
        studentId: 'student-03',
        termId: 'term-2569-1',
        kind: 'deduction',
        requestedDelta: -15,
        appliedDelta: -15,
        scoreBefore: 100,
        scoreAfter: 85,
        ruleId: 'rule-bullying',
        reason: 'เหตุการณ์ตัวอย่างสำหรับทดสอบกระบวนการติดตาม',
        occurredAt: daysAgo(5, 11),
        actorId: 'acc-teacher-01',
      },
    ],
    additionRequests: [
      {
        id: 'request-demo-01',
        studentId: 'student-01',
        teacherId: 'teacher-01',
        requestedPoints: 3,
        reason: 'ปฏิบัติตามแผนปรับพฤติกรรมครบตามเงื่อนไข',
        status: 'pending',
        createdAt: daysAgo(0, 9),
      },
    ],
    appeals: [],
    seriousCases: [
      {
        id: 'case-demo-01',
        transactionId: 'tx-student-03-a',
        studentId: 'student-03',
        severity: 'serious',
        status: 'following_up',
        guardianContactRequired: true,
        guardianContactStatus: 'pending',
        createdAt: daysAgo(5, 11),
        internalNote: 'ข้อมูลตัวอย่าง — นัดหมายทีมดูแลช่วยเหลือนักเรียน',
      },
    ],
  }
}
